REM Sara Carrasquillo
REM Chapter 13

REM Hands-On #1

CREATE VIEW CONTACT AS SELECT NAME AS "Publisher", CONTACT AS "Contact", PHONE AS "Phone #" FROM PUBLISHER;

SELECT * FROM CONTACT;

REM Hands-On #2

CREATE OR REPLACE VIEW CONTACT AS SELECT * FROM PUBLISHER WITH READ ONLY;

SELECT * FROM CONTACT;

DROP VIEW CONTACT;

REM Hands-On #5

CREATE VIEW REORDERINFO AS SELECT B.TITLE, B.ISBN, P.CONTACT, P.PHONE FROM BOOKS B JOIN PUBLISHER P ON B.PUBID = P.PUBID;

SELECT * FROM REORDERINFO;

REM Hands-On #10

DROP VIEW REORDERINFO;

REM Advanced Challenge

CREATE VIEW BOOKPROFIT AS SELECT B.TITLE, SUM(O.QUANTITY) AS QTY, ROUND(SUM(B.RETAIL - B.COST) / SUM(B.COST) * 100) AS "PROFIT %" FROM BOOKS B JOIN ORDERITEMS O ON O.ISBN = B.ISBN GROUP BY TITLE; 

SELECT TITLE, QTY, "PROFIT %" FROM (SELECT B.TITLE, SUM(O.QUANTITY) AS QTY, ROUND(SUM(B.RETAIL - B.COST) / SUM(B.COST) * 100) AS "PROFIT %" FROM BOOKS B JOIN ORDERITEMS O ON O.ISBN = B.ISBN GROUP BY B.TITLE ORDER BY QTY DESC) WHERE ROWNUM <= 5;

DROP VIEW BOOKPROFIT; 
