REM Sara Carrasquillo
REM Chapter 3


REM Hands-On #2
CREATE TABLE EMPLOYEE (Emp# NUMBER(5), Lastname VARCHAR2(50), Firstname VARCHAR2(50), Job_class VARCHAR2(4)); DESCRIBE EMPLOYEES;

DESCRIBE EMPLOYEE;

REM Hands-On #3
ALTER TABLE EMPLOYEE ADD (EmpDate DATE DEFAULT SYSDATE, EndDate DATE);



DESCRIBE EMPLOYEE;
 
REM Hands-On #4

ALTER TABLE EMPLOYEE MODIFY Job_class VARCHAR2(2);



DESCRIBE EMPLOYEE;
 

REM Hands-On #5

ALTER TABLE EMPLOYEE DROP COLUMN EndDate;


DESCRIBE EMPLOYEE;


REM Hands-On #7

CREATE TABLE BOOK_PRICING AS SELECT ISBN AS ID, Cost, Retail, Category FROM BOOKS;



SQL> SELECT * FROM BOOK_PRICING;

SQL> DROP TABLE EMPLOYEE;

SQL> DROP TABLE BOOK_PRICING;


REM Advanced Challenge #1

DESCRIBE ACCTMANAGER;

ALTER TABLE ACCTMANAGER ADD Comm_id NUMBER(2) DEFAULT 10;

ALTER TABLE ACCTMANAGER ADD Ben_id NUMBER(2);

DESCRIBE ACCTMANAGER;
 
CREATE TABLE COMMRATE (Comm_id NUMBER(2), Comm_rank VARCHAR2(15), Rate NUMBER(5, 2));

CREATE TABLE BENEFITS (Ben_id NUMBER(2), Ben_plan CHAR(1), Ben_provider NUMBER(3), Active CHAR(1), CHECK (Active IN ('Y', 'N')));

DESCRIBE ACCTMANAGER;

DESCRIBE COMMRATE;

DESCRIBE BENEFITS;

DROP TABLE ACCTMANAGER;

DROP TABLE COMMRATE;

DROP TABLE BENEFITS;

