REM Sara Carrasquillo
REM Chapter 8

REM Hands-On #4
SELECT CUSTOMER#, LASTNAME, STATE FROM CUSTOMERS WHERE STATE IN ('GA', 'NJ') ORDER BY LASTNAME ASC;

SELECT CUSTOMER#, LASTNAME, STATE FROM CUSTOMERS WHERE STATE = 'GA' OR STATE = 'NJ' ORDER BY LASTNAME ASC;

REM Hands-On #5
SELECT ORDER#, ORDERDATE FROM ORDERS WHERE ORDERDATE <= '01-APR-09';

SELECT ORDER#, ORDERDATE FROM ORDERS WHERE ORDERDATE = '01-APR-09' OR ORDERDATE < '01-APR-09';

REM Hands-On #6
SELECT * FROM AUTHOR WHERE LNAME LIKE '%IN%' ORDER BY LNAME, FNAME;

SELECT LNAME, FNAME FROM AUTHOR WHERE LNAME LIKE '%IN%' ORDER BY LNAME, FNAME;

REM Hands-On #7
SELECT * FROM CUSTOMERS WHERE REFERRED IS NOT NULL;

SELECT LASTNAME, REFERRED FROM CUSTOMERS WHERE REFERRED IS NOT NULL;

REM Hands-On #9
SELECT ISBN, TITLE FROM BOOKS WHERE SUBSTR(TITLE, 2, 1) = 'A' AND SUBSTR(TITLE, 4, 1) = 'N' ORDER BY TITLE DESC;

REM Hands-On #10
SELECT TITLE, PUBDATE FROM BOOKS WHERE PUBDATE BETWEEN '01-JAN-05' AND '31-DEC-05' AND CATEGORY LIKE '%COMPUTER%';

SELECT TITLE, PUBDATE FROM BOOKS WHERE EXTRACT(YEAR FROM PUBDATE) = 2005 AND CATEGORY LIKE '%COMPUTER%';

SELECT TITLE, PUBDATE FROM BOOKS WHERE TO_CHAR(PUBDATE, 'YYYY') = '2005' AND CATEGORY LIKE '%COMPUTER%';

REM Advanced Challenge #1
 SELECT TITLE, (RETAIL - COST) AS PROFIT FROM BOOKS WHERE (RETAIL - COST) >= 10.00 ORDER BY PROFIT DESC;

REM Advanced Challenge #2
SELECT TITLE, CATEGORY, PUBID, RETAIL FROM BOOKS WHERE (CATEGORY LIKE '%COMPUTER%' OR CATEGORY LIKE 'FAMILY LIFE') AND PUBID IN (1, 3) AND RETAIL >= 45.00;