REM Sara Carrasquillo
REM Chapter 6

REM Hands-On #1
CREATE SEQUENCE CUSTOMERS_CUSTOMER_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;

SELECT * FROM user_sequences WHERE sequence_name = 'CUSTOMERS_CUSTOMER_SEQ';


REM Hands-On #2
INSERT INTO CUSTOMERS (Customer#, LastName, FirstName, Zip) VALUES (CUSTOMERS_CUSTOMER_SEQ.NEXTVAL, 'Shoulders', 'Frank', '23567');

SELECT * FROM CUSTOMERS WHERE LastName = 'Shoulders' AND FirstName = 'Frank' AND Zip = '23567';

DROP SEQUENCE CUSTOMERS_CUSTOMER_SEQ;

DELETE FROM CUSTOMERS WHERE LastName = 'Shoulders' AND FirstName = 'Frank' AND Zip = '23567';

REM Hands-On #3
CREATE SEQUENCE MY_FIRST_SEQ START WITH 5 INCREMENT BY -3 MINVALUE 0 MAXVALUE 5 NOCYCLE NOCACHE;

SELECT * FROM user_sequences WHERE sequence_name = 'MY_FIRST_SEQ';


REM Hands-On #4

SELECT MY_FIRST_SEQ.NEXTVAL FROM DUAL;

SELECT MY_FIRST_SEQ.NEXTVAL FROM DUAL;

SELECT MY_FIRST_SEQ.NEXTVAL FROM DUAL;

-- Sequence has reached its maximum value

REM Hands-On #5
ALTER SEQUENCE MY_FIRST_SEQ MINVALUE -1000;

SELECT * FROM user_sequences WHERE sequence_name = 'MY_FIRST_SEQ';


REM Hands-On #7
CREATE SYNONYM NUMGEN FOR MY_FIRST_SEQ;


REM Hands-On #8

SELECT NUMGEN.CURRVAL FROM DUAL;

DROP SYNONYM NUMGEN;

DROP SEQUENCE MY_FIRST_SEQ;


REM Hands-On #10

CREATE INDEX CUSTOMERS_LASTNAME_IDX ON CUSTOMERS(LASTNAME);

SELECT INDEX_NAME, INDEX_TYPE FROM USER_INDEXES WHERE TABLE_NAME = 'CUSTOMERS';

DROP INDEX CUSTOMERS_LASTNAME_IDX;


REM Hands-On #11

CREATE INDEX ORDERS_SHIPDAYS_IDX ON ORDERS(SHIPDATE);

SELECT INDEX_NAME, INDEX_TYPE FROM USER_INDEXES WHERE TABLE_NAME = 'ORDERS';

DROP INDEX ORDERS_SHIPDAYS_IDX;
