REM Sara Carrasquillo
REM Chapter 12

REM Hands-On #1

SELECT TITLE, RETAIL FROM BOOKS WHERE RETAIL < (SELECT AVG(RETAIL) FROM BOOKS);

REM Hands-On #2

SELECT TITLE, CATEGORY, COST FROM BOOKS b WHERE COST < (SELECT AVG(COST) FROM BOOKS WHERE CATEGORY = b.CATEGORY) ORDER BY CATEGORY;

REM Hands-On #7

SELECT SHIPCITY, SHIPSTATE FROM ORDERS WHERE (NVL(SHIPDATE, SYSDATE) - NVL(ORDERDATE, SYSDATE)) = (SELECT MAX(NVL(SHIPDATE, SYSDATE) - NVL(ORDERDATE, SYSDATE)) FROM ORDERS);


REM Hands-On #8

SELECT CUSTOMER#, LASTNAME, FIRSTNAME FROM CUSTOMERS WHERE CUSTOMER# IN (SELECT O.CUSTOMER# FROM ORDERS O JOIN ORDERITEMS I ON O.ORDER# = I.ORDER# JOIN BOOKS B ON I.ISBN = B.ISBN WHERE B.COST = (SELECT MIN(COST) FROM BOOKS));

REM Hands-On #9

SELECT COUNT(DISTINCT CUSTOMER#) AS "Customer Count" FROM ORDERS WHERE ORDER# IN (SELECT DISTINCT O.ORDER# FROM ORDERS O JOIN ORDERITEMS I ON O.ORDER# = I.ORDER# JOIN BOOKAUTHOR BA ON I.ISBN = BA.ISBN JOIN AUTHOR A ON BA.AUTHORID = A.AUTHORID WHERE A.LNAME = 'AUSTIN' AND A.FNAME = 'JAMES');

REM Hands-On #10

SELECT TITLE FROM BOOKS WHERE PUBID = (SELECT PUBID FROM BOOKS WHERE TITLE = 'THE WOK WAY TO COOK') AND TITLE != 'THE WOK WAY TO COOK';


REM Advanced Challenge #1

SELECT ROUND(SUM((QUANTITY * PAIDEACH) * 0.015), 5) AS SURCHARGE FROM ORDERS O JOIN ORDERITEMS I ON O.ORDER# = I.ORDER#;

REM Advanced Challenge #2

 SELECT SUM(PAIDEACH * QUANTITY * 0.04) AS UNCOLLECTABLE FROM ORDERITEMS WHERE ORDER# IN (SELECT DISTINCT ORDER# FROM ORDERITEMS WHERE PAIDEACH > (SELECT AVG(PAIDEACH) FROM ORDERITEMS));
