REM Sara Carrasquillo
REM Chapter 10

REM Hands-On #2
SELECT LASTNAME, FIRSTNAME, NVL2(REFERRED, 'REFERRED', 'NOT REFERRED') AS REFERRAL FROM CUSTOMERS;
REM Hands-On #4
SELECT TITLE, ROUND(((RETAIL - COST) / COST * 100)) || '%' AS PROFIT , RETAIL, COST FROM BOOKS;

REM Hands-On #6
SELECT TITLE, RPAD('*', 12 - LENGTH(COST) + 1, '*') || COST AS COST FROM BOOKS;

REM Hands-On #8
SELECT TITLE, PUBDATE, TRUNC(MONTHS_BETWEEN(SYSDATE, PUBDATE)) AS AGE FROM BOOKS ORDER BY PUBDATE DESC;


REM Advanced Challenge #1

SELECT TITLE AS "Title", CATEGORY AS "Category", ROUND(RETAIL, 2) AS "Current Price", ROUND(RETAIL + CASE WHEN CATEGORY = 'Computer' THEN 0.10 * RETAIL WHEN CATEGORY = 'Fitness' THEN 0.15 * RETAIL WHEN CATEGORY = 'Self-Help' THEN 0.25 * RETAIL ELSE 0.03 * RETAIL END, 2) AS "Revised Price" FROM BOOKS ORDER BY CATEGORY, TITLE;


